ccpitcms/urls.py
from django.conf.urls import url,include
from auth import views as auth_views
from admin import views as admin_views
from front import views as front_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$',front_views.index,name="front-index"),
    url(r'^login/',auth_views.login,name='login'),
    url(r'^register/',auth_views.register,name="register"),
    url(r'^checkUser/',auth_views.checkUser,name="checkUser"),
    url(r'^logout/',auth_views.logout,name="logout" ),
    url(r'^test/',auth_views.test,name="test"),
    url(r'^admin/$', admin_views.index, name="admin-index"),
    url(r'^admin/agencies/', admin_views.agencies, name="admin-agencies"),
    # url(r'^admin/addAgency/',admin_views.addAgency,name="admin-add-agency1"),
    url(r'^admin/addAgency/(\d+)/$',admin_views.addAgency,name="admin-add-agency"),
    url(r'^admin/editAgency/(\d+)/$',admin_views.editAgency,name="admin-edit-agency"),
    url(r'^admin/users/$',admin_views.users, name="admin-users"),
    url(r'^admin/addUser/$',admin_views.addUser,name="admin-add-user"),
    url(r'^admin/test/', admin_views.test, name="admin-test"),
    url(r'^admin/test2/', admin_views.test2, name="admin-test2"),
    url(r'^admin/editUser/(\d+)/$',admin_views.editUser,name="admin-edit-user"),
    url(r'^admin/rules/$',admin_views.rules, name="admin-rules"),
    url(r'^admin/addRule/(\d+)/$',admin_views.addRule,name="admin-add-rule"),
    url(r'^admin/editRule/(\d+)/$',admin_views.editRule,name="admin-edit-rule"),
    url(r'^admin/roles/$',admin_views.roles, name="admin-roles"),
    url(r'^admin/addRole/$',admin_views.addRole,name="admin-add-role"),
    url(r'^admin/editRole/(\d+)/$',admin_views.editRole,name="admin-edit-role"),
    url(r'^admin/setRole/(\d+)/$',admin_views.setRole,name="admin-set-role"),
    url(r'^admin/access/(\d+)/$',admin_views.access,name="admin-access"),
    url(r'^admin/test3/(\d+)/$',admin_views.test3,name="admin-test3"),
    url(r'^admin/testCheck/(.+)/$',admin_views.testCheck,name="admin-test-check"),

    url(r'^event/',include('event.urls')),
    url(r'^front/',include('front.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/urls.py
from django.conf.urls import url
from event import views as event_views

urlpatterns = [    
    url(r'^$',event_views.index,name="event-index"),
    url(r'^add/$',event_views.add,name="event-add"),
    url(r'^edit/(\d+)/$',event_views.edit,name="event-edit"),
    url(r'^show/(\d+)/$',event_views.show,name="event-show"),
    url(r'^agendas/(\d+)/$',event_views.agendas,name="event-agendas"),
    url(r'^addAgenda/(\d+)/$',event_views.addAgenda,name="event-add-agenda"),
    url(r'^editAgenda/(\d+)/$',event_views.editAgenda,name="event-edit-agenda"),
    url(r'^deleteAgenda/(\d+)/$',event_views.deleteAgenda,name="event-delete-agenda"),
]

event/models.py
from django.db import models
from PIL import Image
from django.utils.encoding import force_text, python_2_unicode_compatible
import uuid
import os

def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('images/', filename)


# Create your models here.
@python_2_unicode_compatible
class Event(models.Model):
	user = models.ForeignKey('auth.User')
	name = models.CharField(u'活动名称',max_length=50)
	ename = models.CharField(u'Event Name',max_length=50)
	hosts = models.CharField(u'主办',max_length=254)
	organizer = models.CharField(u'承办',max_length=254)
	contact = models.CharField(u'联系人',max_length=50)
	address = models.CharField(u'联系地址',max_length=254)
	phone = models.CharField(u'电话',max_length=50)
	email = models.EmailField(u'电子邮件')
	website = models.URLField(u'网址')
	city = models.ForeignKey('City')
	venue = models.CharField(u'场馆',max_length=254)
	vaddress = models.CharField(u'地址',max_length=254)
	category = models.ForeignKey('Category')
	start_at = models.DateTimeField(u'开始时间')
	end_at = models.DateTimeField(u'结束时间')	
	intro = models.TextField(u'简介')
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)
	status = models.SmallIntegerField(default=1)
	verfied = models.BooleanField(u'审核状态',default=False)
	image = models.ImageField(u'活动海报',upload_to=get_file_path)


	def __str__(self):
		return self.name

		


@python_2_unicode_compatible
class City(models.Model):
	city = models.CharField(u'城市',max_length=50)
	encity = models.CharField(u'City',max_length=50)

	def __str__(self):
		return self.city


@python_2_unicode_compatible
class Category(models.Model):
	name = models.CharField(u'分类',max_length=50)
	ename = models.CharField(u'Category',max_length=50)

	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Agenda(models.Model):
	event = models.ForeignKey('Event')
	day = models.DateField(u'日期')
	start_time = models.TimeField(u'开始时间')
	end_time = models.TimeField(u'结束时间')
	subject = models.CharField(u'主题',max_length=60)
	place = models.CharField(u'地点',max_length=100)
	sort = models.SmallIntegerField(u'排序',default=1)
	intro = models.TextField(u'简介')

	def __str__(self):
		return self.subject

event/forms.py
from django import forms
from django.forms import ModelForm
from event.models import Event,City,Agenda

class EventForm(ModelForm):

	class Meta:
		model = Event
		fields = ['id','name','ename','hosts','organizer','contact','address','phone','email','website','venue','vaddress','start_at','end_at','intro','image','category','city']
	
	# user = forms.CharField(label='',widget=forms.HiddenInput())
	# image = forms.ImageField()


class AgendaForm(ModelForm):

	class Meta:
		model = Agenda
		fields = ['id','day','start_time','end_time','subject','place','sort','intro']

	

event/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect 
from django.template.response import TemplateResponse
from event.models import Event,Agenda
from auth.models import User
from .forms import EventForm,AgendaForm
from admin.extpaginator import extpaginator
from django.core.urlresolvers import reverse,resolve
from PIL import Image

# Create your views here.

def index(request):
	p = request.GET.get('p')
	k = request.GET.get('k')
	if p == None:
		p = 1
	if k == None:
		k = ''

	if k != '':
		events = Event.objects.filter(name__contains=k)
	else:
		events = Event.objects.all()
	paginator = extpaginator(events, 10)
	pagestr = paginator.pagestr(p,{'k':k})
	try:
		pevents = paginator.page(p)
	except PageNotAnInteger:
		pevents = paginator.page(1)
	except EmptyPage:
		pevents = paginator.page(paginator.num_pages)
	return TemplateResponse(request, 'event/index.html',{'events':pevents, 'pagestr':pagestr})

def add(request):
	if request.method == "POST":
		form = EventForm(request.POST,request.FILES)
		if form.is_valid():
			newEvent = form.save(commit=False)
			newEvent.user = User.objects.get(id=request.session['user_id'])
			try:
				newEvent.save()
				return HttpResponse('Add Event Successfully!')
			except :
				return HttpResponse('Error')
	else:
		form = EventForm()
	return TemplateResponse(request, 'event/add.html',{'form':form})

def edit(request,id):
	if request.method == "POST":
		a = Event.objects.get(id=request.POST['id'])
		form = EventForm(request.POST,request.FILES,instance=a)		
		if form.is_valid():
			try:
				form.save()
			except :
				return HttpResponse('Error')
		return HttpResponseRedirect(reverse('event-index'))
	else:
		event = Event.objects.get(id=id)
		form = EventForm(instance=event)
		return TemplateResponse(request, 'event/edit.html',{'form':form,'id':id})

def show(request,id):
	event = Event.objects.get(id=id)
	return TemplateResponse(request, 'event/show.html',{'event':event})
	# return HttpResponse('show')

def agendas(request,id):
	agendas = Agenda.objects.filter(event__id=id)
	return TemplateResponse(request,'event/agendas.html',{'agendas':agendas,'event_id':id})

def addAgenda(request,event_id):
	if request.method == "POST":
		form = AgendaForm(request.POST)
		if form.is_valid():
			newAgenda = form.save(commit=False)
			newAgenda.event = Event.objects.get(id=event_id)
			try:
				newAgenda.save()
				return HttpResponse('Add Event Agenda Successfully!')
			except :
				return HttpResponse('Error')
	else:
		form = AgendaForm()
	return TemplateResponse(request, 'event/addAgenda.html',{'form':form})

def editAgenda(request,id):
	if request.method == "POST":
		agenda = Agenda.objects.get(id=request.POST['id'])
		form = AgendaForm(request.POST,instance=agenda)		
		if form.is_valid():
			try:
				form.save()
			except :
				return HttpResponse('Error')
		return HttpResponseRedirect(reverse('event-agendas',args=[agenda.event.id]))
	else:
		agenda = Agenda.objects.get(id=id)
		form = AgendaForm(instance=agenda)
		return TemplateResponse(request, 'event/editAgenda.html',{'form':form,'id':id})

def deleteAgenda(request,id):
	agenda = Agenda.objects.get(id=id)
	event_id = agenda.event.id
	agenda.delete()
	return HttpResponseRedirect(reverse('event-agendas',args=[event_id]))

event/templates/event/add.html
{% extends 'base.html' %}

{% block title %}新增活动{% endblock %}

{% block content %}
<link href="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" type="text/css"></link>
<link rel="stylesheet" type="text/css" href="/static/plugins/bootstrap-datetimepicker/css/datetimepicker.css">

<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					新增活动
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">Home</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">活动管理</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>新增活动</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>					
		</div>
			
		<div class="row"><div class="col-md-9"><div class="form">
			<form method='post' class="horizontal-form" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
					<div class="">
						<div class="form-group"><div class="row">
							<div class="control-label col-md-2" style="text-align:right">{{ field.label}}</div>
							<div class="controls col-md-10">
								{{field}}
								<span class="help-block">{{field.errors}}</span>
							</div>

						</div></div>
					</div>
				{% endfor %}
				
				<div class="form-actions center">					
					<button type="submit" class="btn blue"><i class="icon-ok"></i> 添 加</button>
					<button type="button" class="btn" id="cancel-btn">取 消</button>
				</div>
			</form>
		</div></div></div>	
		
	</div>

</div>

{% endblock %}

{% block script %}
<script src="/static/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>	
<script src="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script src="/static/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="/static/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js"></script>
<script>
	jQuery("#cancel-btn").click(function(){
		history.back();
	});

	jQuery("#id_intro").wysihtml5({"image":false});

	jQuery("#id_start_at,#id_end_at").datetimepicker({
		format:"yyyy-mm-dd",
		autoclose:true,
		todayBtn:true,
		language:"zh-CN",
		pickerPosition:'top-right',
		minView:'month',
		maxView:'month'
	});


</script>

{% endblock %}


event/templates/event/addAgenda.html
{% extends 'base.html' %}

{% block title %}新增日程{% endblock %}

{% block content %}
<link href="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" type="text/css"></link>
<link rel="stylesheet" type="text/css" href="/static/plugins/bootstrap-datetimepicker/css/datetimepicker.css">
<link rel="stylesheet" type="text/css" href="/static/plugins/bootstrap-timepicker/compiled/timepicker.css">

<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					新增日程
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">Home</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">日程管理</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>新增日程</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>					
		</div>
			
		<div class="row"><div class="col-md-9"><div class="form">
			<form method='post' class="horizontal-form" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
					<div class="">
						<div class="form-group"><div class="row">
							<div class="control-label col-md-2" style="text-align:right">{{ field.label}}</div>
							<div class="controls col-md-10">
								{{field}}
								<span class="help-block">{{field.errors}}</span>
							</div>

						</div></div>
					</div>
				{% endfor %}
				
				<div class="form-actions center">					
					<button type="submit" class="btn blue"><i class="icon-ok"></i> 添 加</button>
					<button type="button" class="btn" id="cancel-btn">取 消</button>
				</div>
			</form>
		</div></div></div>	
		
	</div>

</div>

{% endblock %}

{% block script %}
<script src="/static/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>	
<script src="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script src="/static/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="/static/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js"></script>
<script src="/static/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>


<script>

	// FormComponents.init();


	jQuery("#cancel-btn").click(function(){
		history.back();
	});


	jQuery("#id_day").datetimepicker({
		format:"yyyy-mm-dd",
		autoclose:true,
		todayBtn:true,
		language:"zh-CN",
		pickerPosition:'bottom-right',
		minView:'month',
		maxView:'month'
	});

	// jQuery("#id_start_time,#id_end_time").timepicker({
	// 	'setTime':'08:00 AM',
	// 	'defaultTime':'current',
	// 	'autoclose': true
	// });


</script>

{% endblock %}


event/templates/event/agendas.html
{% extends 'base.html' %}

{% block title %}权限列表{% endblock %}

{% block content %}
<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					日程管理
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">Home</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">日程管理</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>日程列表</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>					
		</div>
			
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN EXAMPLE TABLE PORTLET-->
				<div class="portlet-body">
					<div class="table-toolbar">
						<div class="btn-group">
							<a href="{% url 'event-add-agenda' event_id %}" class="btn green">
								新增日程 <i class="fa fa-plus"></i>
							</a>
						</div>								
					</div>

					<table class="table table-striped table-bordered table-hover">
						<thead>
							<tr>										
								<th class="center">序号</th>
								<th class="hidden-480 center">日期</th>
								<th class="hidden-480 center">起止时间</th>
								<th class="center">主题</th>
								<th class="center">地点</th>
								<th>操作</th>
							</tr>
						</thead>

						<tbody>
							{% for item in agendas %}
								<tr class="odd gradeX">		
									<td class="center">{{ item.id }}</td>
									<td class="center">
										{{item.day|date:"Y-m-d"}}	
									</td>
									<td class="hidden-480 center">{{ item.start_time }} -- {{item.end_time}}</td>
									<td class="center hidden-480">{{ item.subject }}</td>
									<td class="center">
										{{ item.place }}
									</td>
									
									<td >
										<a href="{% url 'event-edit-agenda' item.id %}">编辑</a> | 
										<a href="{% url 'event-delete-agenda' item.id %}">删除</a>
									</td>
								</tr>
							{% endfor %}	
						</tbody>

					</table>
				</div>
				<!-- END EXAMPLE TABLE PORTLET-->

			</div>

		</div>	
		
	</div>
	
</div>

{% endblock %}


event/templates/event/edit.html
{% extends 'base.html' %}

{% block title %}编辑活动{% endblock %}

{% block content %}
<link href="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" type="text/css"></link>
<link rel="stylesheet" type="text/css" href="/static/plugins/bootstrap-datetimepicker/css/datetimepicker.css">

<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					编辑活动
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">Home</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">活动管理</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>编辑活动</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>					
		</div>
			
		<div class="row"><div class="col-md-9"><div class="form">
			<form method='post' class="horizontal-form" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
					<div class="">
						<div class="form-group"><div class="row">
							<div class="control-label col-md-2" style="text-align:right">{{ field.label}}</div>
							<div class="controls col-md-10">
								{{field}}
								<span class="help-block">{{field.errors}}</span>
							</div>

						</div></div>
					</div>
				{% endfor %}
				
				<div class="form-actions center">
					<input type="hidden" name="id" value=" {{id}} ">				
					<button type="submit" class="btn blue"><i class="icon-ok"></i> 编 辑</button>
					<button type="button" class="btn" id="cancel-btn">取 消</button>
				</div>
			</form>
		</div></div></div>	
		
	</div>

</div>

{% endblock %}

{% block script %}
<script src="/static/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>	
<script src="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script src="/static/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="/static/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js"></script>
<script>
	jQuery("#cancel-btn").click(function(){
		history.back();
	});

	jQuery("#id_intro").wysihtml5({"image": false});

	jQuery("#id_start_at,#id_end_at").datetimepicker({
		format:"yyyy-mm-dd",
		autoclose:true,
		todayBtn:true,
		language:"zh-CN",
		pickerPosition:'top-right',
		minView:'month',
		maxView:'month'
	});
</script>

{% endblock %}


event/templates/event/editAgenda.html
{% extends 'base.html' %}

{% block title %}编辑日程{% endblock %}

{% block content %}
<link href="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.css" rel="stylesheet" type="text/css"></link>
<link rel="stylesheet" type="text/css" href="/static/plugins/bootstrap-datetimepicker/css/datetimepicker.css">
<link rel="stylesheet" type="text/css" href="/static/plugins/bootstrap-timepicker/compiled/timepicker.css">

<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					编辑日程
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">Home</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">日程管理</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>编辑日程</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>					
		</div>
			
		<div class="row"><div class="col-md-9"><div class="form">
			<form method='post' class="horizontal-form" enctype="multipart/form-data">
				{% csrf_token %}
				{% for field in form %}
					<div class="">
						<div class="form-group"><div class="row">
							<div class="control-label col-md-2" style="text-align:right">{{ field.label}}</div>
							<div class="controls col-md-10">
								{{field}}
								<span class="help-block">{{field.errors}}</span>
							</div>

						</div></div>
					</div>
				{% endfor %}
				
				<div class="form-actions center">				<input type="hidden" name="id" value=" {{id}} ">	
					<button type="submit" class="btn blue"><i class="icon-ok"></i> 编 辑</button>
					<button type="button" class="btn" id="cancel-btn">取 消</button>
				</div>
			</form>
		</div></div></div>	
		
	</div>

</div>

{% endblock %}

{% block script %}
<script src="/static/plugins/bootstrap-wysihtml5/wysihtml5-0.3.0.js"></script>	
<script src="/static/plugins/bootstrap-wysihtml5/bootstrap-wysihtml5.js"></script>
<script src="/static/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="/static/plugins/bootstrap-datetimepicker/js/locales/bootstrap-datetimepicker.zh-CN.js"></script>
<script src="/static/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js"></script>


<script>

	jQuery("#cancel-btn").click(function(){
		history.back();
	});


	jQuery("#id_day").datetimepicker({
		format:"yyyy-mm-dd",
		autoclose:true,
		todayBtn:true,
		language:"zh-CN",
		pickerPosition:'bottom-right',
		minView:'month',
		maxView:'month'
	});

	// jQuery("#id_start_time,#id_end_time").timepicker({
	// 	'setTime':'08:00 AM',
	// 	'defaultTime':'current',
	// 	'autoclose': true
	// });


</script>

{% endblock %}


event/templates/event/index.html
{% extends 'base.html' %}

{% block title %}活动列表{% endblock %}

{% block content %}
<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					活动管理
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="">首页</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>
						<a href="">活动管理</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>我的活动</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>					
		</div>
			
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN EXAMPLE TABLE PORTLET-->
				<div class="portlet-body">
					<div class="table-toolbar"><div class="row">
						<div class="btn-group col-md-8">
							<a href="{% url 'event-add' %}" class="btn green">
								新增活动 <i class="fa fa-plus"></i>
							</a>
						</div>
						<form action="{% url 'event-index' %}" method="GET">
						<div class="col-md-4">
							<div class="input-group"> 						
								<input type="text" class="form-control" name="k" >
								<span class="input-group-btn">
									<button class="btn blue" type="submit"><i class="fa fa-search"></i></button>
								</span>
							</div>
						</div></form>

					</div></div>

					<table class="table table-striped table-bordered table-hover">
						<!-- <thead>
							<tr>	 -->									
								<!-- <th class="center">序号</th> -->
								<!-- <th class="center">缩略图</th>
								<th class="right">活动名称</th>
								<th class="center">分类</th>
								<th class="center">城市</th>
								<th class="center">起始时间</th> -->
								<!-- <th class="center">状态</th>	 -->
						<!-- 		<th>操作</th>
							</tr>
						</thead> --> 

						<tbody>
							{% for item in events %}
								<tr class="odd gradeX">		
									<!-- <td class="center">{{ item.id }}</td> -->
									<td class="center" style="width:180px">
										<img src="/uploads/{{item.image}}" width="160" height="120">
									</td>
									<td class="left">
										<h4><a href="{% url 'event-show' item.id %}">{{ item.name }}</a></h4>
										<p>起始时间：{{item.start_at|date:"Y-m-d"}} -- {{item.end_at|date:"Y-m-d"}}</p>
										<p>{{item.category.name}} | {{item.city.city}}</p> 
										<p>
											<a href="{% url 'event-edit' item.id %}">
											<i class="fa fa-pencil"></i> 编辑
										</a> | 									
										<a href="{% url 'event-agendas' item.id %}"><i class="fa fa-calendar"></i> 日程管理</a> | 
										<a href=""><i class="fa fa-file-text-o"></i>  设计报名表</a> |
										<a href=""><i class="fa fa-rss"></i> 新闻管理</a> | 
										<a href=""><i class="fa fa-puzzle-piece"></i> 参会者管理</a> | 
										<a href=""><i class="fa fa-magic"></i> 现场签到管理</a>
										</p>
									</td>
									
								</tr>
							{% endfor %}	
						</tbody>

					</table>
					<div>
						{{ pagestr|safe }}
					</div>
				</div>
				<!-- END EXAMPLE TABLE PORTLET-->

			</div>

		</div>	
		
	</div>
	
</div>

{% endblock %}


event/templates/event/show.html
{% extends 'base.html' %}

{% block title %}show{% endblock %}

{% block content %}
<div class="page-content-wrapper">
	<!-- BEGIN PAGE -->
	<div class="page-content">
		<div class="row">
			<div class="col-md-12">
				<!-- BEGIN PAGE TITLE & BREADCRUMB-->
				<h3 class="page-title">
					Dashboard
				</h3>
				<ul class="breadcrumb">
					<li>
						<i class="icon-home"></i>
						<a href="index.html">Home</a> 
						<i class="icon-angle-right"></i>
					</li>
					<li>Dashboard</li>

				</ul>
				<!-- END PAGE TITLE & BREADCRUMB-->
			</div>					
		</div>
			
		<div id="dashboard">
			<h1>{{event.name}}</h1>
			<p>{{event.intro|safe}}</p>
			<div>
				<img src="{{event.image.url}}">
			</div>
		</div>	
		
	</div>
	
</div>

{% endblock %}
